t = table(IntrNbr, SmartCareID, PatientOffset, Hospital, DTStartDate, DTDateNum, ...
Type, DaysWithMeasures, AvgMeasuresPerDay, DTScaledDateNum, Offset, DataWindowCompleteness, ...
LowerBound, UpperBound);

